### ISSUE TITLE
Commercial use / LLaMa Dependency?

### ISSUE THREAD

**Issue by brianjking** [OpenGVLab/InternGPT#11]
It seems this has a dependency on LLaMa base weights and Segment Anything. Is that correct?

Is there a way to separate this out and use OpenAI or an actually commercially viable model such as MosaicML's MPT-7B-Instruct?

**Comment by liu-zhy** [comment]
Thanks for your reminder! We are glad to hear suggestions from you!

This project is built for non-commercial purposes. 

Although our Husky is trained from LLaMa_weights, we only released delta_weights (Husky_weights - LLaMa_weights) instead of directly exposing the Husky_weights.

We have checked the [License](https://github.com/facebookresearch/segment-anything/blob/main/LICENSE) of SAM. It seems it is ok to distribute the weights of SAM.

Separating these dependencies from our repo is definitely viable, but we may not place this plan as our first priority currently due to the limited time. As a result, we expect more contributions and PRs from the community!

Hope you enjoy our project!
