### ISSUE TITLE
About the choice of visual models

### ISSUE THREAD

**Issue by zhiyuanyou** [OpenGVLab/InternGPT#52]
Hi~
Thanks for your great work!

I have read your paper and went through in detail this script (https://github.com/OpenGVLab/InternGPT/blob/main/iGPT/controllers/ConversationBot.py). 

I noticed that the used visual models are determined by some **_key words_**, _i.e._, _remove_ & _erase_ means _LDMInpainting_, _describe_ & _introduce_ means _HuskyVQA_. This is a direct and effective way. 

However, I wonder what will happen if the user does not input such words. For example, the user could input `take out some objects` instead of `remove some objects` for object removing. 

Thanks in advance.

**Comment by liu-zhy** [comment]
Thank you for your attention! 

Your idea is quite interesting. To be frank, we are working on this issue. However, natural language is usually ambiguous. For example, `take out some objects` could mean that you want to remove the object from the image, or that others want to extract the region of the dog in the image. Interestingly, `the region of the dog` is also ambiguous, it can be a bounding box obtained by a detector or a mask calculated by a segmentor. Therefore, as you can see, this problem is very intractable.

Good News: we will release InternGPT v2 as soon as possible. We believe the upgraded version can partly address your issue.

Please stay tuned for our work.  🍻🍻🍻🍻🍻🍻

**Comment by zhiyuanyou** [comment]
Thanks for your response. 

I understand that if we give all choices to GPT for the determination of visual models, the processing results will be somewhat unsatisfying. 

Currently, it is still a tradeoff between generalization and quality.

**Comment by liu-zhy** [comment]
Yep! I can not agree with you more. The next version of iGPT can address this issue.
